# docker-compose.yml
version: '3.8'

services:
  load-service:
    image: happyrobot-loads
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./allowed_references.csv:/app/allowed_references.csv
    command: python find_available_loads.py

  carrier-service:
    image: happyrobot-carriers
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    command: python verify_carrier.py

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - load-service
      - carrier-service